config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  
  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params.require(:comment).permit(:body))
        redirect_to post_path(@post)
    end

    def edit
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
    end

    def update
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.update(params.require(:comment).permit(:body))
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:text))
    @post.save
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params.require(:post).permit(:text))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p>
    <strong> Comment: </strong>
    <%= comment.body %><br>
    <%= link_to  "Edit", edit_post_comment_path(@post, comment) %> |
    <%= link_to  "Delete", [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %> <br>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1> Editing comment </h1>

<%= form_with(model: [ @post, @comment ], local: true) do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to  "Back", post_path(@post) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with( model: @post , local: true) do |form| %>
    <p>
        <%= form.label :text %> <br>
        <%= form.text_area :text %><br>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<h1> Editing Post </h1>

<%= render  "form" %>

<%= link_to  "Back", posts_path %>

app/views/posts/index.html.erb
<h1>My Posts</h1>
<%= link_to  "New Post", new_post_path %>

<ul>
    <% @posts.each do |post| %>
        <li>
            <strong> Content: </strong>
            <%= post.text %><br>
            <%= link_to  "Show", post_path(post) %>
        </li> <br>
    <% end %>
</ul>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= render  "form" %>

<%= link_to  "Back", posts_path %>

app/views/posts/show.html.erb
<h1> Post #<%= @post.id %> </h1>

<p>
    <strong>Content: </strong>
    <%= @post.text %> <br>

    <strong>Created </strong>
    <%= time_ago_in_words(@post.created_at) %> ago<br>

    <strong>Updated </strong>
    <%= time_ago_in_words(@post.updated_at) %> ago<br>

</p>

<h2> Comments </h3>
<%= render  @post.comments %>

<h3> Add Comment </h3>
<%= render  "comments/form" %>

<%= link_to 'Edit', edit_post_path %> | 
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %><br>
<%= link_to 'All posts', posts_path %>